version: 2.1
orbs: 
  docker: circleci/docker@1.4.0
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.8
      - checkout
      - docker/check
      - docker/build:
          image: snowdogg/artgenerator
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          image: snowdogg/artgenerator
          tag: "latest,$CIRCLE_SHA1"
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip install ecs-deploy
      - run:
          command: ecs deploy $ECS_CLUSTER_NAME $ECS_SERVICE --image website-service snowdogg/artgenerator:$CIRCLE_SHA1 --region $AWS_REGION
workflows:
  version: 2
  test-build-push-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build-and-push
