version: 2.1
orbs: 
  docker: circleci/docker@1.4.0
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build-and-push:
    executor: docker/docker
    auth:
      username: snowdogg
      password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
        version: 19.03.8
      - checkout
      - docker/check
      - docker/build:
          image: snowdogg/artgenerator
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          image: snowdogg/artgenerator
          tag: "latest,$CIRCLE_SHA1"
workflows:
  version: 2
  test:
    jobs:
      - test
      - build-and-push:
          requires:
            - test