version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  test:
    jobs:
      - test

