version: 2.1
orbs: 
  docker: circleci/docker@1.4.0
  aws-ecs: circleci/aws-ecs
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: echo "$CIRCLE_BRANCH"
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.8
      - checkout
      - docker/check
      - docker/build:
          image: snowdogg/artgenerator
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          image: snowdogg/artgenerator
          tag: "latest,$CIRCLE_SHA1"
  # deploy: 
  #   aws-ecs/depolo
  #     aws-region: 

workflows:
  version: 2
  test-build-push-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      # - deploy
      #     requires:
      #       - test